Repository Goose-sDream/golaping-client, pull requests merged in 2025-01, with the labels that each got.

#6 #3 set: 패키지 설치 및 eslint, prettier 파일 수정
  .gitignore
  .prettierrc
  babel.config.js
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/index.tsx
  webpack.config.js
Labels: 초기설정

#8 #1 feat: 투표 생성 화면 UI 구현
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/Select.tsx
  src/components/create/createForm.tsx
  src/components/create/steps/BasicForm.tsx
  src/components/create/steps/LandingForm.tsx
  src/types/voteTypes.ts
Labels: enhancement

#11 feat: main 브랜치 최신화
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/Select.tsx
  src/components/create/createForm.tsx
  src/components/create/steps/BasicForm.tsx
  src/components/create/steps/LandingForm.tsx
  src/components/create/steps/OptionForm.tsx
  src/components/create/steps/ShareVote.tsx
  src/index.tsx
  src/page.tsx
  src/pages/CreatePage.tsx
  src/pages/VotePage.tsx
  src/types/voteTypes.ts
Labels: enhancement

#14 #7 feat: 공통 컴포넌트 스타일 적용
  package.json
  pnpm-lock.yaml
  src/assets/Arrow.svg
  src/components/common/Button.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Input.tsx
  src/components/common/Stepper.tsx
  src/components/create/CreateForm.tsx
  src/components/create/steps/BasicForm.tsx
  src/components/create/steps/ShareVote.tsx
  src/styles/color.ts
  svg.d.ts
  tsconfig.json
  webpack.config.js
Labels: enhancement

#16 #1 feat: 랜딩 페이지 스타일 적용
  src/assets/PurpleLogo.svg
  src/components/create/CreateForm.tsx
  src/components/create/steps/LandingForm.tsx
Labels: enhancement

#18 #1 fix: 폼 인풋 간격 수정 및 validation 스타일 추가
  src/components/common/Dropdown.tsx
  src/components/common/Input.tsx
  src/components/common/Stepper.tsx
  src/components/create/CreateForm.tsx
  src/components/create/steps/BasicForm.tsx
Labels: enhancement

#21 #20 set: 절대 경로 import 설정
  src/components/common/Button.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Input.tsx
  src/components/common/Select.tsx
  src/components/common/Stepper.tsx
  src/components/common/index.ts
  src/components/create/CreateForm.tsx
  src/components/create/steps/BasicForm.tsx
  src/components/create/steps/LandingForm.tsx
  src/components/create/steps/OptionForm.tsx
  src/components/create/steps/ShareVote.tsx
  src/components/create/steps/index.ts
  src/pages/CreatePage.tsx
  tsconfig.json
  webpack.config.js
Labels: 초기설정

#25 #19 feat: axios 연결을 위한 request 모듈 구현
  package.json
  pnpm-lock.yaml
  src/services/instance.ts
  src/services/requests.ts
  webpack.config.js
Labels: enhancement

#27 #19 feat: 투표 생성 API 연결
  src/App.tsx
  src/components/create/CreateForm.tsx
  src/components/create/steps/BasicForm.tsx
  src/components/create/steps/OptionForm.tsx
  src/services/requests.ts
  src/types/apiTypes.ts
  src/types/voteTypes.ts
Labels: enhancement

#29 #28 fix: TimePicker 버그 수정 + 스타일 수정
  src/components/create/createForm.tsx
  src/components/create/steps/OptionForm.tsx
  src/components/create/steps/TimePicker.tsx
  src/constants/create.ts
Labels: bug

#35 #19 feat: 투표 생성 시, websocketUrl과 sessionId 저장하도록 설정
  eslint.config.mjs
  src/atoms/createAtom.ts
  src/components/create/CreateForm.tsx
  src/hooks/useCookies.ts
  src/hooks/useCustomHooks.ts
  src/hooks/useSessionId.ts
  src/hooks/useWebsocketUrl.ts
  src/pages/VotePage.tsx
Labels: enhancement
